server:
  port: 8080

#-- NAME --#
spring:
  application:
    name: demo

  #-- DATASOURCE --#
  datasource:
    url: jdbc:postgresql://152.207.165.99:5432/demo
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  #-- JPA --#
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true

# -- SWAGGER --#
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui
