server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: demo-service
          uri: lb://demo-service
          predicates: 
            - Path=/demo-service/**
          filters:
            - AuthFilter
        - id: otherdemo-service
          uri: lb://otherdemo-service
          predicates: 
            - Path=/otherdemo-service/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates: 
            - Path=/auth-service/**