server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: demo
          uri: lb://demo
          predicates: 
            - Path=/api/**
        - id: otherdemo
          uri: lb://otherdemo
          predicates: 
            - Path=/api/**
        - id: auth
          uri: lb://auth
          predicates: 
            - Path=/auth/**
