server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: dev
          uri: https://github.com/branlysoler/demo-aplication
          search-paths: config-data
  application:
    name: config-demo
